# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20146ba6d1c39c484f902cc21c181cf0c8c41010dcc6aedaf836a84c2a7ffd374fe7c05ad74689949dd26051008cca57654b0fcf197bb005117443e3733b95e9

test:
  secret_key_base: 6393c59b69485c19373fd7286317d2d9bfc813b3af0258a69fe0337fbb2e8f22ed134322da8f66405b215e23e42458190776cc03229e4dcd2b29121894db1b35

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
